services:
  app1:
    container_name: app1
    image: app
    build: .
    environment:
    - NAME=app1
    ports:
    - "8080:8080"
  otel-collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.86.0
    ports:
    - 4317:4317
    configs:
    - source: collector
      target: /etc/otelcol-contrib/config.yaml
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.50.1
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.enable-remote-write-receiver
    ports:
    - 9090:9090
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.56
    ports:
    - "16686:16686"
  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.0
    ports:
    - 8888:3000

configs:
  collector:
    file: ./config.yaml
