name: app

services:
  front:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - front

  back:
    image: back
    build: .
    depends_on:
      - db
    restart: always
    secrets:
      - connection_string
    networks:
      - front
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    restart: always
    networks:
      - db

configs:
  nginx:
    file: ./default.conf

secrets:
  connection_string:
    environment: "DB_CONN"

networks:
  db:
  front:

volumes:
  db-data:
