- hosts: all
  connection: local
  become: True
  vars:
    user: ""
    password: ""
    pg:
      login_host: provider2.local
      login_user: "{{user}}"
      login_password: "{{password}}"
      db: postgres
  module_defaults:
    community.postgresql.postgresql_db: '{{ pg }}'
    community.postgresql.postgresql_user: '{{ pg }}'
    community.postgresql.postgresql_query: '{{ pg }}'
    community.postgresql.postgresql_table: '{{ pg }}'

  tasks:
  - ansible.builtin.file:
      path: /home/vagrant/html
      owner: 101
      group: 101
    tags: html
  - ansible.builtin.copy:
      src: /home/vagrant/index.html
      dest: /home/vagrant/html/index.html
      owner: 101
      group: 101
    tags: html
  - community.postgresql.postgresql_db:
      name: app
    tags: sql
  - community.postgresql.postgresql_user:
      name: app
      db: app
      priv: ALL
    tags: sql
  - community.postgresql.postgresql_table:
      db: app
      name: users
      columns:
      - id serial primary key
      - name varchar(50)
      - email varchar(100)
    tags: sql
